#This is a movit contoller connecting follow_joint_trajectory controller with JointTrajectoryController
controller_list:
  - name: robot_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
    - base_rotation_joint
    - shoulder_rotation
    - elbow_rotation
    - arm_rotation
    - gripper_pitch
  - name: hand_ee_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
    - gripper_rotation
    - palm_joint
