controller_list:
  - name: fake_rover_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_rotation_joint
      - shoulder_rotation
      - elbow_rotation
      - arm_rotation
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_pitch
      - gripper_rotation
      - palm_joint
initial:  # Define initial robot poses per group
  - group: rover_arm
    pose: home