arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_rotation_joint
    - shoulder_rotation
    - elbow_rotation
    - arm_rotation
  gains:
    base_rotation_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_rotation:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_rotation:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_rotation:
      p: 100
      d: 1
      i: 1
      i_clamp: 1