// Generated by gencpp from file rover_msgs/drive_msg.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_DRIVE_MSG_H
#define ROVER_MSGS_MESSAGE_DRIVE_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct drive_msg_
{
  typedef drive_msg_<ContainerAllocator> Type;

  drive_msg_()
    : direction()
    , speed(0.0)
    , mode()  {
    }
  drive_msg_(const ContainerAllocator& _alloc)
    : direction(_alloc)
    , speed(0.0)
    , mode(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _direction_type;
  _direction_type direction;

   typedef double _speed_type;
  _speed_type speed;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::rover_msgs::drive_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::drive_msg_<ContainerAllocator> const> ConstPtr;

}; // struct drive_msg_

typedef ::rover_msgs::drive_msg_<std::allocator<void> > drive_msg;

typedef boost::shared_ptr< ::rover_msgs::drive_msg > drive_msgPtr;
typedef boost::shared_ptr< ::rover_msgs::drive_msg const> drive_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::drive_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::drive_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rover_msgs::drive_msg_<ContainerAllocator1> & lhs, const ::rover_msgs::drive_msg_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction &&
    lhs.speed == rhs.speed &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rover_msgs::drive_msg_<ContainerAllocator1> & lhs, const ::rover_msgs::drive_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rover_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::drive_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::drive_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::drive_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::drive_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::drive_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::drive_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::drive_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd483411e489ff081154f8cefaf4e01e";
  }

  static const char* value(const ::rover_msgs::drive_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd483411e489ff08ULL;
  static const uint64_t static_value2 = 0x1154f8cefaf4e01eULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::drive_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/drive_msg";
  }

  static const char* value(const ::rover_msgs::drive_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::drive_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string direction\n"
"float64 speed\n"
"string mode\n"
;
  }

  static const char* value(const ::rover_msgs::drive_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::drive_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.speed);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct drive_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::drive_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::drive_msg_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.direction);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_DRIVE_MSG_H
