#Instead of using TAB for indentation, use two spaces at the place of one TAB#Controller to control robot arm joints
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [base_rotation_joint, shoulder_rotation, elbow_rotation, arm_rotation, gripper_pitch]
#Controller to control end effector joints
hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [gripper_rotation, palm_joint]
#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
